### PR TITLE
Implement enhancement for #20

### PR DESCRIPTION
**Pull request by OneHoopyFrood**
Ok, really works now. Unit tests weren't quite enough before.
This has been tested in a real project and confirmed working.

### CODE REVIEW

**Comment by OneHoopyFrood** [comment]
Referencing #20. Finishes what #21 started

**Comment by OneHoopyFrood** [comment]
This also adds an enhancement to the `getRoutes` function that checks each file pulled to see if it has a path and method property, treating that as confirmation that it's intended to be a route.

**Comment by sitraka-hq** [comment]
Can I merge and close this PR @OneHoopyFrood ?

**Comment by OneHoopyFrood** [comment]
Sorry, was away for holidays. Back today! Thanks for the merge!

**Comment by sitraka-hq** [comment]
> Sorry, was away for holidays. Back today! Thanks for the merge!

Happy new year :fireworks:

**Pull request merged**
